### ISSUE TITLE
Image Crop is Not working (IOS)

### ISSUE THREAD

**Issue by MITDD6338** [Michaelvilleneuve/react-native-perspective-image-cropper#31]
when clicking the image then cropper is not open
anyone can help us?
@abstruse9 @SL-A-SH

"react": "16.8.3",
"react-native": "0.59.10",
"react-native-perspective-image-cropper": "^0.4.3",
"react-native-svg": "^9.13.3"

Platform: IOS
I was Use
https://github.com/Michaelvilleneuve/react-native-document-scanner

then same page display image
and then I can use this package with the same page
https://github.com/Michaelvilleneuve/react-native-perspective-image-cropper

![Image from iOS](https://user-images.githubusercontent.com/31823903/68386432-ff11ff80-0181-11ea-8794-939dfd7ab8b9.png)

but crop code is not working

**I Share my issues below Link** 
https://drive.google.com/file/d/1FVrTt0N5cKh9EsqGnI4Y7mH_iLlEPCMA/view?usp=sharing

@Michaelvilleneuve

**Comment by Zayyar-DSS** [comment]
For Scanner, use this one [ https://github.com/Woonivers/react-native-perspective-image-cropper ] instead of Michael's. It works on both iOS and android but you'll get only black and white photo in Android.

For Cropper, I can initiate it in iOS but after you've cloned your repo in another Mac, it doesn't work. Has pod issue. So available options are [ https://github.com/ivpusic/react-native-image-crop-picker ] and [ https://github.com/ggunti/react-native-amazing-cropper ].

Cheers mate.

**Comment by ahmetozalp** [comment]
Simulator not working.

**Comment by Rishu2505** [comment]
Image crop is not working even in real ios device same error as above.

**Comment by ahmetozalp** [comment]
my project working no problem.

**Comment by Michaelvilleneuve** [comment]
One of the params  you sent to the native call is nil
